name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create APK using PWA Builder
        run: |
          npx pwabuilder build --platform android
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Toolbox-APK
          path: out/android/*.apk
